kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: firebase-sync-backend-dev
spec:
  replicas: 1
  template:
    metadata:
      name: firebase-sync
      labels:
        app: firebase-sync
        role: backend
        env: dev
    spec:
      containers:
        - name: firebase-sync
          image: DOCKER_IMAGE
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: DATABASE_URL
              value: "https://inception-65767.firebaseio.com"
            - name: ADMIN_SERVICE_ACCOUNT
              value: "/admin-service-account/inception-65767-firebase-adminsdk-ntlor-e096246512.json"
          volumeMounts:
            - name: images-store
              mountPath: /app/downloads
            - name: admin-service-account
            mountPath: /admin-service-account
      volumes:
        - name: images-store
          persistentVolumeClaim:
            claimName: shared-images-store
        - name: admin-service-account
          secret:
            secretName: pwned-admin-service-account